Repository NeurodataWithoutBorders/pynwb, pull requests merged in 2018-11, with the labels that each got.

#736 fix __repr__ and tests
  src/pynwb/core.py
  tests/integration/ui_write/base.py
  tests/unit/pynwb_tests/test_core.py
Labels: critical

#744 Shortcut loop in ObjectMapper.__is_reftype to improve perfomance
  src/pynwb/form/build/map.py
Labels: bug

#743 Spatial series shape
  src/pynwb/behavior.py
  src/pynwb/data/nwb.behavior.yaml
Labels: enhancement, minor, schema (non-breaking)
