Repository NeurodataWithoutBorders/pynwb, pull requests merged in 2022-08, with the labels that each got.

#1516 Enh/ `ImageSeries`: add checks when `external_file` is used
  CHANGELOG.md
  requirements-min.txt
  requirements.txt
  src/pynwb/core.py
  src/pynwb/image.py
  tests/back_compat/test_read.py
  tests/integration/hdf5/test_image.py
  tests/integration/hdf5/test_ophys.py
  tests/unit/test_image.py
  tests/unit/test_ophys.py
Labels: category: enhancement

#1545 Fix HDMF intersphinx
  docs/source/conf.py
Labels: topic: docs

#1543 Fix broken link to install instructions in READM
  README.rst
Labels: category: bug, topic: docs
